export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const DELETE_FROM_FAVORITES = "DELETE_FROM_FAVORITES";
export const GET_LEGENDS = "GET_LEGENDS";
export const GET_STARSHIPS = "GET_STARSHIPS";
export const GET_PLANETS = "GET_PLANETS";
